KYPHOSIS PREDICTION

In [1]:
#Importing the dependencies
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

Data collection and analysis

In [2]:
#loading the kyphosis dataset to the pandas Dataframe
kyphosis_dataset = pd.read_csv('Kyphosis.csv')
pd.read_csv?

In [3]:
#first 5 data of the dataset
kyphosis_dataset.head()

#kyphosis- a factor with levels absent/present indiacting if a kyphosis was present after the operation
#age-in months
#number- the number of vertebrae involved
#start- the number of 1st vertebrae operated on

#an adult body has total 24 vertebrae

Kyphosis  Age  Number  Start
0   absent   71       3      5
1   absent  158       3     14
2  present  128       4      5
3   absent    2       5      1
4   absent    1       4     15

In [4]:
#number of rows and column in the dataset
kyphosis_dataset.shape

(81, 4)

In [5]:
#getting the statistical measures of the data
kyphosis_dataset.describe()
#25% means that around 25% of value are less than 26.000 or 3.0000 depending upon the column they represent
#its not percentage its the percentile

Age     Number      Start
count   81.000000  81.000000  81.000000
mean    83.654321   4.049383  11.493827
std     58.104251   1.619423   4.883962
min      1.000000   2.000000   1.000000
25%     26.000000   3.000000   9.000000
50%     87.000000   4.000000  13.000000
75%    130.000000   5.000000  16.000000
max    206.000000  10.000000  18.000000

In [6]:
kyphosis_dataset['Kyphosis'].value_counts()

absent     64
present    17
Name: Kyphosis, dtype: int64

In [7]:
kyphosis_dataset.groupby('Kyphosis').mean()
#in case of present: in 97 months that is 8.8years the 5th vertebrae was involved in kyphosis syndrome,
# in 7th vertebrae it was first operated

Age    Number      Start
Kyphosis                                
absent    79.890625  3.750000  12.609375
present   97.823529  5.176471   7.294118

In [8]:
#separating data and labels
x=kyphosis_dataset.drop('Kyphosis',axis=1)
y=kyphosis_dataset['Kyphosis']

In [9]:
print(x)

    Age  Number  Start
0    71       3      5
1   158       3     14
2   128       4      5
3     2       5      1
4     1       4     15
..  ...     ...    ...
76  157       3     13
77   26       7     13
78  120       2     13
79   42       7      6
80   36       4     13

[81 rows x 3 columns]


In [10]:
print(y)

0      absent
1      absent
2     present
3      absent
4      absent
       ...   
76    present
77     absent
78     absent
79    present
80     absent
Name: Kyphosis, Length: 81, dtype: object


Data Standardization

In [11]:
scaler = StandardScaler()

In [12]:
scaler.fit(x)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [13]:
standardized_data = scaler.transform(x)

In [14]:
print(standardized_data)

[[-0.21914343 -0.65203532 -1.33790708]
 [ 1.28749437 -0.65203532  0.51634056]
 [ 0.7679641  -0.03068401 -1.33790708]
 [-1.41406306  0.59066729 -2.16201714]
 [-1.43138074 -0.03068401  0.72236808]
 [-1.43138074 -1.27338662  0.92839559]
 [-0.39232019 -1.27338662  1.13442311]
 [-0.80794441 -0.65203532  0.92839559]
 [ 0.50819896 -1.27338662  0.92839559]
 [-0.42695554  1.21201859  0.10428553]
 [-0.02864899  0.59066729  0.51634056]
 [ 1.11431761 -0.65203532  0.92839559]
 [-1.13698025  0.59066729 -1.95598962]
 [-1.43138074 -0.03068401  0.10428553]
 [ 1.46067113 -0.65203532  1.34045062]
 [-1.43138074 -0.65203532  0.92839559]
 [-0.0979197   1.21201859  0.72236808]
 [ 1.58189486  0.59066729  0.31031305]
 [-0.06328435  0.59066729  0.92839559]
 [-0.98112117 -0.03068401 -0.51379701]
 [-1.06770955 -1.27338662  0.92839559]
 [ 0.36965755  1.21201859 -1.33790708]
 [ 0.21379847 -0.65203532  0.10428553]
 [ 0.81991712 -1.27338662 -1.74996211]
 [-1.18893328  1.83336989 -1.95598962]
 [-1.29283933  0.59066729

In [15]:
x = standardized_data
y = kyphosis_dataset['Kyphosis']

In [16]:
print(x)
print(y)

[[-0.21914343 -0.65203532 -1.33790708]
 [ 1.28749437 -0.65203532  0.51634056]
 [ 0.7679641  -0.03068401 -1.33790708]
 [-1.41406306  0.59066729 -2.16201714]
 [-1.43138074 -0.03068401  0.72236808]
 [-1.43138074 -1.27338662  0.92839559]
 [-0.39232019 -1.27338662  1.13442311]
 [-0.80794441 -0.65203532  0.92839559]
 [ 0.50819896 -1.27338662  0.92839559]
 [-0.42695554  1.21201859  0.10428553]
 [-0.02864899  0.59066729  0.51634056]
 [ 1.11431761 -0.65203532  0.92839559]
 [-1.13698025  0.59066729 -1.95598962]
 [-1.43138074 -0.03068401  0.10428553]
 [ 1.46067113 -0.65203532  1.34045062]
 [-1.43138074 -0.65203532  0.92839559]
 [-0.0979197   1.21201859  0.72236808]
 [ 1.58189486  0.59066729  0.31031305]
 [-0.06328435  0.59066729  0.92839559]
 [-0.98112117 -0.03068401 -0.51379701]
 [-1.06770955 -1.27338662  0.92839559]
 [ 0.36965755  1.21201859 -1.33790708]
 [ 0.21379847 -0.65203532  0.10428553]
 [ 0.81991712 -1.27338662 -1.74996211]
 [-1.18893328  1.83336989 -1.95598962]
 [-1.29283933  0.59066729

train test split

In [17]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=42)

In [18]:
print(x.shape, x_train.shape, x_test.shape)

(81, 3) (56, 3) (25, 3)


In [19]:
classifier = svm.SVC(kernel='linear')

In [20]:
#training the support vector machine
classifier.fit(x_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

Model Evaluation 

Accuracy Score

In [21]:
#accuracy score on the training data
x_train_prediction = classifier.predict(x_train)
training_data_accuracy = accuracy_score(x_train_prediction, y_train)

In [22]:
print('Accuracy score of the training data : ', training_data_accuracy)

Accuracy score of the training data :  0.8214285714285714


In [23]:
#accuracy score on the test data
x_test_prediction = classifier.predict(x_test)
test_data_accuracy = accuracy_score(x_test_prediction, y_test)

In [24]:
print('Accuracy score of the test data : ', test_data_accuracy)

Accuracy score of the test data :  0.76


Making a predictive System

In [25]:
input_data=(71,3,5)

#chaging the input data to numpy array
input_data_as_numpy_array = np.asarray(input_data)

#reshape the array as we are predicting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

#standardize the input data
std_data = scaler.transform(input_data_reshaped)
print(std_data)

prediction = classifier.predict(std_data)
print(prediction)

if (prediction[0]=='absent'):
    print('person is not suffering from kyphosis')
else:
    print('person is suffering from kyphosis')

[[-0.21914343 -0.65203532 -1.33790708]]
['absent']
person is not suffering from kyphosis
